CREATE SCHEMA IF NOT EXISTS musiguessr_schema AUTHORIZATION app_user;

GRANT ALL PRIVILEGES ON SCHEMA musiguessr_schema TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA musiguessr_schema GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA musiguessr_schema GRANT ALL ON SEQUENCES TO app_user;